/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubprojetosRouteImport } from './routes/_authenticated/subprojetos'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedInteligenciaRouteImport } from './routes/_authenticated/inteligencia'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated/fluxo-caixa'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as PRelatorioTokenRouteImport } from './routes/p.relatorio.$token'
import { Route as AuthenticatedProjetosProjetoIdRouteImport } from './routes/_authenticated/projetos.$projetoId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubprojetosRoute =
  AuthenticatedSubprojetosRouteImport.update({
    id: '/subprojetos',
    path: '/subprojetos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteligenciaRoute =
  AuthenticatedInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PRelatorioTokenRoute = PRelatorioTokenRouteImport.update({
  id: '/p/relatorio/$token',
  path: '/p/relatorio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosProjetoIdRoute =
  AuthenticatedProjetosProjetoIdRouteImport.update({
    id: '/projetos/$projetoId',
    path: '/projetos/$projetoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/subprojetos': typeof AuthenticatedSubprojetosRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/p/relatorio/$token': typeof PRelatorioTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/subprojetos': typeof AuthenticatedSubprojetosRoute
  '/': typeof AuthenticatedIndexRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/p/relatorio/$token': typeof PRelatorioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/subprojetos': typeof AuthenticatedSubprojetosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/p/relatorio/$token': typeof PRelatorioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistente'
    | '/auditoria'
    | '/configuracoes'
    | '/fluxo-caixa'
    | '/inteligencia'
    | '/relatorios'
    | '/roadmap'
    | '/subprojetos'
    | '/projetos/$projetoId'
    | '/p/relatorio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistente'
    | '/auditoria'
    | '/configuracoes'
    | '/fluxo-caixa'
    | '/inteligencia'
    | '/relatorios'
    | '/roadmap'
    | '/subprojetos'
    | '/'
    | '/projetos/$projetoId'
    | '/p/relatorio/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistente'
    | '/_authenticated/auditoria'
    | '/_authenticated/configuracoes'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/inteligencia'
    | '/_authenticated/relatorios'
    | '/_authenticated/roadmap'
    | '/_authenticated/subprojetos'
    | '/_authenticated/'
    | '/_authenticated/projetos/$projetoId'
    | '/p/relatorio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PRelatorioTokenRoute: typeof PRelatorioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subprojetos': {
      id: '/_authenticated/subprojetos'
      path: '/subprojetos'
      fullPath: '/subprojetos'
      preLoaderRoute: typeof AuthenticatedSubprojetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia': {
      id: '/_authenticated/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AuthenticatedInteligenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/relatorio/$token': {
      id: '/p/relatorio/$token'
      path: '/p/relatorio/$token'
      fullPath: '/p/relatorio/$token'
      preLoaderRoute: typeof PRelatorioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$projetoId': {
      id: '/_authenticated/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof AuthenticatedProjetosProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedInteligenciaRoute: typeof AuthenticatedInteligenciaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSubprojetosRoute: typeof AuthenticatedSubprojetosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjetosProjetoIdRoute: typeof AuthenticatedProjetosProjetoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedInteligenciaRoute: AuthenticatedInteligenciaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSubprojetosRoute: AuthenticatedSubprojetosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjetosProjetoIdRoute: AuthenticatedProjetosProjetoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PRelatorioTokenRoute: PRelatorioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
