/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubprojetosRouteImport } from './routes/subprojetos'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'

const SubprojetosRoute = SubprojetosRouteImport.update({
  id: '/subprojetos',
  path: '/subprojetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/relatorios': typeof RelatoriosRoute
  '/roadmap': typeof RoadmapRoute
  '/subprojetos': typeof SubprojetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/relatorios': typeof RelatoriosRoute
  '/roadmap': typeof RoadmapRoute
  '/subprojetos': typeof SubprojetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/relatorios': typeof RelatoriosRoute
  '/roadmap': typeof RoadmapRoute
  '/subprojetos': typeof SubprojetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/fluxo-caixa'
    | '/relatorios'
    | '/roadmap'
    | '/subprojetos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/fluxo-caixa'
    | '/relatorios'
    | '/roadmap'
    | '/subprojetos'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/fluxo-caixa'
    | '/relatorios'
    | '/roadmap'
    | '/subprojetos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RoadmapRoute: typeof RoadmapRoute
  SubprojetosRoute: typeof SubprojetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subprojetos': {
      id: '/subprojetos'
      path: '/subprojetos'
      fullPath: '/subprojetos'
      preLoaderRoute: typeof SubprojetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  RelatoriosRoute: RelatoriosRoute,
  RoadmapRoute: RoadmapRoute,
  SubprojetosRoute: SubprojetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
